version: '3.8'

services:
  # Servicio de Backend (FastAPI)
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - ENV=dev

  # Servicio de Frontend (Streamlit)
  web:
    build:
      context: ./web
    ports:
      - "8501:8501"
    volumes:
      - ./web:/app
    depends_on:
      - api # Se asegura que la API levante antes que la web