# Dockerfile.api
FROM python:3.11-slim

WORKDIR /app

# Copiamos requirements desde la raíz (sin ../)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos todo el código y la carpeta models
COPY . .

EXPOSE 8000

# Arrancamos FastAPI usando la ruta de módulos correcta
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]